
target 'WatchKitColorsExample WatchKit Extension' do
  platform :watchos, '2.0'
  use_frameworks!

  # When I'm testing new versions of the library, use a local podspec
  # pod 'WatchKitColors', :path => '~/code/HJS/HJSKit/HJSUtils_Support/UIColor-WatchKitColors'
  # Here's the "normal" podspec.
  pod 'WatchKitColors', :git => 'https://github.com/HiddenJester/UIColor-WatchKitColors.git'
end
